version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql # 使用命名卷持久化数据
    networks:
      - app-network

  node-express:
    build:
      context: ./node-express
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8801:80"
    environment:
      - URL=http://node-express:3000
    depends_on:
      - node-express
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: # 声明一个名为 mysql_data 的卷
